In [1]:
import pandas as pd
import numpy as np
import pickle as pk
import os
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import zlib

# manually specify the GPUs to use
#os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
#os.environ["CUDA_VISIBLE_DEVICES"]="0"

import torch
import math
import random
import MinkowskiEngine as ME
from torch.utils.data import Dataset, DataLoader
from glob import glob
from glob import iglob
import os.path as osp, h5py, tqdm
import utils
from Core import utils
from Core.trainers import Trainer

# System
import time
# Externals
import torch.nn as nn
import torch.optim as optim
from torch.utils.tensorboard import SummaryWriter
import tqdm, psutil
from scipy.special import softmax
from sklearn.metrics import classification_report, confusion_matrix, explained_variance_score

/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/__init__.py:42: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  "It is recommended to set it below 24.",
/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/__init__.py:224: UserWarning: The MinkowskiEngine was compiled with CPU_ONLY flag. If you want to compile with CUDA support, make sure `torch.cuda.is_available()` is True when you install MinkowskiEngine.
  "If you want to compile with CUDA support, make sure `torch.cuda.is_available()` is True when you install MinkowskiEngine.",


In [2]:
# from PDG to label
def pdg2tos(pdg):
    if pdg==13 or pdg==-13 or pdg==211 or pdg==-211:
        return 0 # track
    if pdg==2212 or pdg==321 or pdg==-321:
        return 0 # heavy track
    if pdg==11 or pdg==-11 or pdg==22:
        return 1 # shower
    return -1

In [3]:
# generate events
graph=0
voxel_size=0.05 # cm
numGraphs = len(list(iglob('/eos/home-a/aabedabu/physics_gnn/physics_processed_data_collection/Leigh_grid_data_40000/1GeV_?/mc_sce_dd/*/*.gz')))
for graph_path in iglob('/eos/home-a/aabedabu/physics_gnn/physics_processed_data_collection/Leigh_grid_data_40000/1GeV_?/mc_sce_dd/*/*.gz'):
#numGraphs = len(list(iglob('../../data_grid_leigh/9*/*.gz')))
#for graph_path in iglob('../../data_grid_leigh/9*/*.gz'):
    if graph % 100 == 0:
      print(str(graph+1) + " out of " + str(numGraphs))
    example = {}
    with open(graph_path[:-3]+'.info', 'rb') as info_file:
        lines = info_file.readlines()
        values = {'X':float(lines[0]),
                  'Y':float(lines[1]),
                  'Z':float(lines[2]),
                  'Energy':float(lines[3]),
                  'Interaction':int(lines[4]),
                  'PDG':int(lines[5]),
                  'NumberOfNodes':int(lines[6]),
                  'NumberOfFeatures':int(lines[7])
                  }
        #print(values)
        
    nnodes = values['NumberOfNodes']
    nfeatures = values['NumberOfFeatures']
    
    # spatial coordinates
    XYZ=np.zeros(shape=(nnodes,3),dtype=float)
        
    # all nodes are usable by deafault
    usable = [True]*nnodes
        
    features = []
    X = []
    Y = []
    Z = []
    labels = []
    # iterate over nodes and save spatial coordinates
    with open(graph_path, 'rb') as graph_file:
        codes = np.fromstring(zlib.decompress(graph_file.read()), dtype=np.float32, sep='')
        for node_id in range(nnodes):
            # label
            label = pdg2tos(codes[node_id*(3+nfeatures+1)+(3+nfeatures)])
            if label == -1:
                continue
                
            # features
            feature = []
            for j in range(3,3+values['NumberOfFeatures']):
                feature.append(codes[node_id*(3+values['NumberOfFeatures']+1)+j])
            
            x = codes[node_id*(3+nfeatures+1)+0]
            y = codes[node_id*(3+nfeatures+1)+1]
            z = codes[node_id*(3+nfeatures+1)+2]
            
            x = int(x/voxel_size)
            y = int(y/voxel_size)
            z = int(z/voxel_size)
            xyz = np.dstack((X,Y,Z)).reshape(len(X),3)
            if [x,y,z] in xyz:
                continue
            
            # coordinates
            X.append(x)
            Y.append(y)
            Z.append(z)
            labels.append(label)
            
            ## Removing charge over distance feature
            #del feature[-3:] #delete last three
            
            # get the charge
            #del feature[0:3] 
            #del feature[1:6]
            
            # get the angle
            #del feature[0:5]
            #del feature[1:4]
            
            # Get only the charge over distance
            del feature[0:6]
            
            features.append(feature)
            
    X = np.array(X)
    Y = np.array(Y)
    Z = np.array(Z)
    coords=np.dstack((X,Y,Z)).reshape(X.shape[0],3)
    features = np.array(features)
    labels = np.array(labels).reshape(X.shape[0],1)
    
    example['x'] = features
    example['c'] = coords
    example['y'] = labels
    
    torch.save(example, 'sparse_data_protodune/event{}.pt'.format(graph))
    graph+=1

1 out of 40101


/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:40: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead


101 out of 40101
201 out of 40101
301 out of 40101
401 out of 40101
501 out of 40101
601 out of 40101
701 out of 40101
801 out of 40101
901 out of 40101
1001 out of 40101
1101 out of 40101
1201 out of 40101
1301 out of 40101
1401 out of 40101
1501 out of 40101
1601 out of 40101
1701 out of 40101
1801 out of 40101
1901 out of 40101
2001 out of 40101
2101 out of 40101
2201 out of 40101
2301 out of 40101
2401 out of 40101
2501 out of 40101
2601 out of 40101
2701 out of 40101
2801 out of 40101
2901 out of 40101
3001 out of 40101
3101 out of 40101
3201 out of 40101
3301 out of 40101
3401 out of 40101
3501 out of 40101
3601 out of 40101
3701 out of 40101
3801 out of 40101
3901 out of 40101
4001 out of 40101
4101 out of 40101
4201 out of 40101
4301 out of 40101
4401 out of 40101
4501 out of 40101
4601 out of 40101
4701 out of 40101
4801 out of 40101
4901 out of 40101
5001 out of 40101
5101 out of 40101
5201 out of 40101
5301 out of 40101
5401 out of 40101
5501 out of 40101
5601 out of 40101
5

In [4]:
# collate function
def collate_sparse_minkowski_saul(batch):
    #coords, feats = ME.utils.sparse_collate([d['c'] for d in batch], [d['x'] for d in batch])
    #coords = ME.utils.batched_coordinates([d['c'] for d in batch], dtype=torch.float32)#([d['c'].int() for d in batch])
    voxel_size=1.0
    coords = [(d['c']/voxel_size).int() for d in batch]
    feats = torch.cat([d['x'] for d in batch])
    y = torch.cat([d['y'] for d in batch])
    ret = { 'f': feats, 'c': coords, 'y': y }
    return ret

In [5]:
# dataset
class SparseEventProtoDUNE(Dataset):
    def __init__(self, root, shuffle=True, **kwargs):
        '''Initialiser for SparseEventProtoDUNE class'''
        
        self.root = root
        self.data_files = self.processed_file_names
        if shuffle:
            random.shuffle(self.data_files) 
        self.total_events = len(self.data_files)
        
    @property
    def raw_dir(self):
        return f'{self.root}/raw'
    
    @property
    def processed_dir(self):
        return f'{self.root}'

    @property
    def raw_file_names(self):
        ret = []
        for subdir in glob(f'{self.raw_dir}/*'):
            ret += glob(f'{subdir}/*.root')
        return ret
    
    @property
    def processed_file_names(self):
        return glob(f'{self.processed_dir}/*.pt')
    
    def __len__(self):
        return len(self.data_files)
    
    def __len__(self):
        return self.total_events
    
    def __getitem__(self, idx):
        data = torch.load(self.data_files[idx])
        c = torch.FloatTensor(data['c'])
        x = torch.FloatTensor(data['x'])
        y = torch.LongTensor(data['y'])

        del data
        return { 'x': x, 'c': c, 'y': y}
    
    def vet_files(self):
        for f in self.data_files:
            _, ext = osp.splitext(f)
            if ext != '.pt':
                print('Extension not recognised! Skipping')
                continue
            try:
                torch.load(f)
            except:
                print(f'File {f} is bad! Removing...')
                os.remove(f)

In [6]:
# generate dataset
dataset=SparseEventProtoDUNE("sparse_data_protodune")

In [7]:
number_images = len(dataset)
first_image = dataset[0]
print('Number of images train:', number_images)
#print('First image train:', first_image)¡

Number of images train: 40101


In [8]:
"""
This module defines a generic trainer for simple models and datasets. 
"""

# Locals
from Core.models import get_model
from Core.trainers.base import base
from Core.loss import get_loss
from Core.activation import get_activation
from Core.optim import get_optim
from Core.scheduler import get_scheduler
from Core.metrics import get_metrics
from Core.utils import *

class Trainer(base):
    """Trainer code for basic classification problems with categorical cross entropy."""

    def __init__(self, train_name="test1", summary_dir="summary",
        empty_cache = None, **kwargs):
        super(Trainer, self).__init__(train_name=train_name, **kwargs)
        self.writer = SummaryWriter(f"{summary_dir}/{train_name}")
        self.empty_cache = empty_cache
        
    def arrange_sparse_minkowski(self, data):
        return ME.SparseTensor(
                           features=data['f'], 
                           coordinates=ME.utils.batched_coordinates(data['c'], dtype=torch.float32)#,
                           #quantization_mode=ME.SparseTensorQuantizationMode.RANDOM_SUBSAMPLE, 
                           #device=self.device
                           )
    
    def arrange_truth(self, data):
        return data['y']

    def build_model(self, optimizer_params=None, scheduler_params=None,
        loss_params=None, metric_params=None, name="NodeConv",
        arrange_data="arrange_sparse_minkowski", arrange_truth="arrange_sparse",
        **model_args):
        """Instantiate our model"""

        self.train_name = name
            
        # Construct the model
        #torch.cuda.set_device(self.device)
        self.model = get_model(name=name, **model_args)
        #self.model = self.model.to(self.device)        
        
        # Construct the loss function
        #self.loss_func = get_loss(**loss_params)
        self.loss_func = nn.CrossEntropyLoss()#get_loss(func="categorical_cross_entropy")

        # Construct the optimizer
        #self.optimizer = get_optim(model_params=self.model.parameters(), **optimizer_params)
        self.optimizer = optim.SGD(self.model.parameters(), lr=0.1, momentum=0.9, weight_decay=0.0001)
        #self.scheduler = get_scheduler(self.optimizer, **scheduler_params)
        self.scheduler = optim.lr_scheduler.CosineAnnealingLR(self.optimizer, T_max=3)
        '''
        scheduler_params = {"ReduceLROnPlateau":{"factor":0.9,"patience":0.3},
                            "StepLR":{"step_size":5, "gamma":0.8}}
        self.scheduler = get_scheduler(self.optimizer, "ReduceLROnPlateau")
        '''
        self.scheduler = None
        
        'Classification'
        # Configure metrics
        '''
        metrics=metric_params["metrics"]
        metric_args = metric_params[metrics]
        self.metrics = get_metrics(metrics)(**metric_args)
        '''
        #self.metrics = get_metrics("Classification")(["track", "heavy_track", "shower"])
        self.metrics = get_metrics("Classification")(["track", "shower"])
        #self.metrics = get_metrics("Classification")(["protons", "muons"])
        #self.batch_metrics = metric_params["include_batch_metrics"]
        self.batch_metrics = "yes"
        
        '''
        # Select function to arrange data
        self.arrange_data = get_arrange_data(arrange_data)
        self.arrange_truth = get_arrange_truth(arrange_truth)
        '''

    def load_state_dict(self, state_dict, **kwargs):
        """Load state dict from trained model"""
        self.model.load_state_dict(torch.load(state_dict, map_location=f"cuda:{self.device}")["model"])

    def train_epoch(self, data_loader, **kwargs):
        """Train for one epoch"""
        self.model.train()
        self.metrics.new_epoch()
        summary = dict()
        sum_loss = 0.
        start_time = time.time()
        # Loop over training batches
        batch_size = data_loader.batch_size
        n_batches = int(math.ceil(len(data_loader.dataset)/batch_size)) #if max_iters_train is None else max_iters_train
        t = tqdm.tqdm(enumerate(data_loader),total=n_batches)
        for i, data in t:
            self.optimizer.zero_grad()
            # Different input shapes for SparseConvNet vs MinkowskiEngine
            batch_input = self.arrange_sparse_minkowski(data)
            batch_output = self.model(batch_input)
            batch_target = self.arrange_truth(data)#.to(self.device)
            batch_target = torch.reshape(batch_target, (len(batch_target),))
            
            batch_loss = nn.functional.cross_entropy(batch_output.F, batch_target, reduction="mean")
            batch_loss.backward()

            # Calculate accuracy
            metrics = self.metrics.train_batch_metrics(batch_output.F, batch_target)
            
            self.optimizer.step()

            sum_loss += batch_loss.item()
            t.set_description("loss = %.5f" % batch_loss.item() )
            t.refresh() # to show immediately the update

            # add to tensorboard summary
            if self.batch_metrics:
                metrics = self.metrics.train_batch_metrics(batch_output.F, batch_target)
                if self.iteration%100 == 0:
                    self.writer.add_scalar("loss/batch", batch_loss.item(), self.iteration)
                    for key, val in metrics.items(): self.writer.add_scalar(key, val, self.iteration)
            self.iteration += 1

            if self.empty_cache is not None and self.iteration % self.empty_cache == 0:
                #torch.cuda.empty_cache()
                print("")

        summary["lr"] = self.optimizer.param_groups[0]["lr"]
        summary["train_time"] = time.time() - start_time
        summary["train_loss"] = sum_loss / n_batches
        self.logger.debug(" Processed %i batches", n_batches)
        self.logger.info("  Training loss: %.3f", summary["train_loss"])
        self.logger.info("  Learning rate: %.5f", summary["lr"])
        return summary
    
    @torch.no_grad()
    def evaluate(self, data_loader, max_iters_eval=None, **kwargs):
        """Evaluate the model"""
        self.model.eval()
        summary = dict()
        sum_loss = 0
        start_time = time.time()
        # Loop over batches
        batch_size = data_loader.batch_size
        n_batches = int(math.ceil(len(data_loader.dataset)/batch_size))
        t = tqdm.tqdm(enumerate(data_loader),total=n_batches)
        true=[]
        pred=[]
        for i, data in t:
            batch_input = self.arrange_sparse_minkowski(data)
            batch_output = self.model(batch_input)
            batch_target = self.arrange_truth(data).to(batch_output.device)
            batch_target = torch.reshape(batch_target, (len(batch_target),))
            
            
            pred+=np.argmax(softmax(batch_output.F.cpu().detach().numpy(),axis=-1), axis=-1).tolist()
            true+=batch_target.cpu().detach().numpy().tolist()
            
            batch_loss = self.loss_func(batch_output.F, batch_target)
            sum_loss += batch_loss.item()
            self.metrics.valid_batch_metrics(batch_output.F, batch_target)
        summary["valid_time"] = time.time() - start_time
        summary["valid_loss"] = sum_loss / n_batches
        self.logger.debug(" Processed %i samples in %i batches",
                          len(data_loader.sampler), n_batches)
        self.logger.info("  Validation loss: %.3f" % (summary["valid_loss"]))
        return summary, np.array(true), np.array(pred)
    
    def train(self, train_data_loader, n_epochs, resume=False, valid_data_loader=None, sherpa_study=None, sherpa_trial=None, **kwargs):
        """Run the model training"""

        # Loop over epochs
        best_valid_loss = 99999
        self.first_epoch = 0
        if resume:
            self.logger.info("Resuming existing training!")
            state_dict = None
            while True:
                state_files = glob(f"{self.output_dir}/checkpoints/*{self.first_epoch:03d}.pth.tar")
                if len(state_files) > 1:
                    raise Exception(f"More than one state file found for epoch {self.first_epoch}!")
                elif len(state_files) == 0:
                    self.logger.info(f"Resuming training from epoch {self.first_epoch}.")
                    self.load_state_dict(state_dict)
                    break
                state_dict = state_files[0]
                self.first_epoch += 1
        n_batches = int(math.ceil(len(train_data_loader.dataset)/train_data_loader.batch_size))
        self.iteration = self.first_epoch * n_batches
        for i in range(self.first_epoch, n_epochs):
            self.logger.info("Epoch %i" % i)
            self.writer.add_scalar("learning_rate", self.optimizer.param_groups[0]["lr"], i+1)
            summary = dict(epoch=i)
            # Train on this epoch
            sum_train = self.train_epoch(train_data_loader, **kwargs)
            summary.update(sum_train)
            # Evaluate on this epoch
            sum_valid = None
            if valid_data_loader is not None:
                sum_valid, true_pid, pred_pid = self.evaluate(valid_data_loader, **kwargs)
                summary.update(sum_valid)

                if sum_valid["valid_loss"] < best_valid_loss:
                    best_valid_loss = sum_valid["valid_loss"]
                    self.logger.debug("Checkpointing new best model with loss: %.3f", best_valid_loss)
                    self.write_checkpoint(checkpoint_id=i,best=True)

            if self.scheduler is not None:
                self.scheduler.step(sum_valid["valid_loss"])

            # Save summary, checkpoint
            self.save_summary(summary)
            if self.output_dir is not None:
                self.write_checkpoint(checkpoint_id=i)

            self.writer.add_scalars('loss/epoch', {
                'train': summary['train_loss'],
                'valid': summary['valid_loss'] }, i+1)
            metrics = self.metrics.epoch_metrics()
            if sherpa_study is not None and sherpa_trial is not None:
                sherpa_study.add_observation(
                trial=sherpa_trial,
                iteration=i,
                objective=metrics["acc/epoch"]["valid"])
            for key, val in metrics.items(): self.writer.add_scalars(key, val, i+1)
            for key, val in metrics.items(): print(key, val)
            if valid_data_loader is not None:
                print(confusion_matrix(pred_pid, true_pid))
            

        return self.summaries
    
def _test():
    t = Trainer(output_dir="./")
    t.build_model()


In [9]:
fulllen = len(dataset)
t_v_split= 0.2
tv_num = math.ceil(fulllen*t_v_split)
#splits = np.cumsum([fulllen-tv_num,0,tv_num])
splits=np.cumsum([fulllen-2*tv_num,0,tv_num, 0, tv_num])
print(splits)
collate = collate_sparse_minkowski_saul

train_dataset = torch.utils.data.Subset(dataset,np.arange(start=0,stop=splits[0]))
valid_dataset = torch.utils.data.Subset(dataset,np.arange(start=splits[1],stop=splits[2]))
test_dataset = torch.utils.data.Subset(dataset,np.arange(start=splits[3],stop=splits[4]))
train_loader = DataLoader(train_dataset, collate_fn=collate, batch_size=32, num_workers=0, shuffle=True)#, pin_memory=True)
valid_loader = DataLoader(valid_dataset, collate_fn=collate, batch_size=32, num_workers=0, shuffle=False)
test_loader = DataLoader(test_dataset, collate_fn=collate, batch_size=32, num_workers=0, shuffle=False)

[24059 24059 32080 32080 40101]


In [10]:
trainer = Trainer(device=0, n_epochs=10, max_iters_train=None, max_iters_eval=None,
                  summary_dir='summary/3d/test', output_dir='./')
name = "MinkUNet14A"
#name = "MinkUNet14B"
#name = "MinkUNet14C"
#name = "MinkUNet14D"
#name = "MinkUNet18A"
#name = "MinkUNet18B"
#name = "MinkUNet18C"
#name = "MinkUNet18D"
#name = "MinkUNet34A"
#name = "MinkUNet34B"
#name = "MinkUNet34C"
#name = "MinkUNet34D"
trainer.build_model(name=name,
                    in_channels=3, out_channels=2, D=3
                   )

In [11]:
# train
trainer.train(train_data_loader=train_loader, valid_data_loader=valid_loader, n_epochs=30)

  0%|          | 0/752 [00:00<?, ?it/s]/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
/usr/local/lib64/python3.6/site-packages/torch/autograd/__init__.py:132: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  allow_unreachable=True)  # allow_unreachable flag
100%|██████████| 251/251 [06:14<00:00,  1.49s/it]


acc/epoch {'train': 91.11030019729618, 'valid': 93.20492389207304}
acc_class/epoch/track {'train': 93.33102688498148, 'valid': 95.53967593843376}
acc_class/epoch/shower {'train': 87.41603771001981, 'valid': 89.17765540593611}
time/epoch {'train': 1497.5179750919342, 'valid': 374.40743613243103}


  0%|          | 0/752 [00:00<?, ?it/s]

[[944189  62005]
 [ 44080 510930]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [05:51<00:00,  1.40s/it]


acc/epoch {'train': 93.32683602915777, 'valid': 93.94127865416691}
acc_class/epoch/track {'train': 94.85503149193492, 'valid': 96.10106155307918}
acc_class/epoch/shower {'train': 90.78462531828096, 'valid': 90.2158185483519}
time/epoch {'train': 1454.5342950820923, 'valid': 351.0187928676605}


  0%|          | 0/752 [00:00<?, ?it/s]

[[949737  56057]
 [ 38532 516878]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [04:20<00:00,  1.04s/it]


acc/epoch {'train': 93.92138004967846, 'valid': 94.16251815906185}
acc_class/epoch/track {'train': 95.18718062747968, 'valid': 96.02122499036193}
acc_class/epoch/shower {'train': 91.8156731129019, 'valid': 90.95639121366298}
time/epoch {'train': 1304.7936642169952, 'valid': 260.42317628860474}


  0%|          | 0/752 [00:00<?, ?it/s]

[[948948  51814]
 [ 39321 521121]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [04:18<00:00,  1.03s/it]


acc/epoch {'train': 94.21527920098148, 'valid': 94.19031721671223}
acc_class/epoch/track {'train': 95.3267676132134, 'valid': 96.33713088238122}
acc_class/epoch/shower {'train': 92.36627636370274, 'valid': 90.48722804506619}
time/epoch {'train': 1154.4650664329529, 'valid': 258.802006483078}


  0%|          | 0/752 [00:00<?, ?it/s]

[[952070  54502]
 [ 36199 518433]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [04:21<00:00,  1.04s/it]


acc/epoch {'train': 94.4608019180967, 'valid': 92.72734376801495}
acc_class/epoch/track {'train': 95.47033202226946, 'valid': 92.30158995172367}
acc_class/epoch/shower {'train': 92.78141056647166, 'valid': 93.46173649715936}
time/epoch {'train': 1102.3669004440308, 'valid': 261.34525847435}


  0%|          | 0/752 [00:00<?, ?it/s]

[[912188  37460]
 [ 76081 535475]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [04:35<00:00,  1.10s/it]


acc/epoch {'train': 94.64702656249565, 'valid': 94.0925080899101}
acc_class/epoch/track {'train': 95.50115705301734, 'valid': 96.17432095917205}
acc_class/epoch/shower {'train': 93.22614832121052, 'valid': 90.5015403143463}
time/epoch {'train': 1103.8550734519958, 'valid': 275.8994097709656}


  0%|          | 0/752 [00:00<?, ?it/s]

[[950461  54420]
 [ 37808 518515]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [03:54<00:00,  1.07it/s]


acc/epoch {'train': 94.86301802562902, 'valid': 94.24655586329526}
acc_class/epoch/track {'train': 95.59322068767592, 'valid': 95.73223484699004}
acc_class/epoch/shower {'train': 93.64829839467752, 'valid': 91.68387338877884}
time/epoch {'train': 1112.2215464115143, 'valid': 234.9256329536438}


  0%|          | 0/752 [00:00<?, ?it/s]

[[946092  47646]
 [ 42177 525289]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [01:25<00:00,  2.95it/s]


acc/epoch {'train': 95.01195919418866, 'valid': 94.14772188644149}
acc_class/epoch/track {'train': 95.63069761604903, 'valid': 94.73149516983736}
acc_class/epoch/shower {'train': 93.98266452501986, 'valid': 93.1407576775725}
time/epoch {'train': 867.8327696323395, 'valid': 85.20453453063965}


  0%|          | 0/752 [00:00<?, ?it/s]

[[936202  39299]
 [ 52067 533636]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [01:26<00:00,  2.90it/s]


acc/epoch {'train': 95.13426013072987, 'valid': 94.51096717661497}
acc_class/epoch/track {'train': 95.69094186412916, 'valid': 95.42280492457013}
acc_class/epoch/shower {'train': 94.20819910014329, 'valid': 92.93811688935045}
time/epoch {'train': 621.8720417022705, 'valid': 86.68237233161926}


  0%|          | 0/752 [00:00<?, ?it/s]

[[943034  40460]
 [ 45235 532475]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [01:25<00:00,  2.95it/s]


acc/epoch {'train': 95.3216840138692, 'valid': 94.20267947045998}
acc_class/epoch/track {'train': 95.80676717432532, 'valid': 96.2147957691681}
acc_class/epoch/shower {'train': 94.51472990609001, 'valid': 90.73193294178223}
time/epoch {'train': 620.8607585430145, 'valid': 85.17957353591919}


  0%|          | 0/752 [00:00<?, ?it/s]

[[950861  53100]
 [ 37408 519835]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [01:25<00:00,  2.94it/s]


acc/epoch {'train': 95.36168719185186, 'valid': 94.22221567456911}
acc_class/epoch/track {'train': 95.79744080239715, 'valid': 94.38401892602116}
acc_class/epoch/shower {'train': 94.63679464831665, 'valid': 93.94311745660502}
time/epoch {'train': 608.9362721443176, 'valid': 85.33984088897705}


  0%|          | 0/752 [00:00<?, ?it/s]

[[932768  34702]
 [ 55501 538233]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [01:24<00:00,  2.95it/s]


acc/epoch {'train': 95.52910948599985, 'valid': 94.21164690841171}
acc_class/epoch/track {'train': 95.89553914830337, 'valid': 96.53697525673678}
acc_class/epoch/shower {'train': 94.91953994140893, 'valid': 90.20063357972545}
time/epoch {'train': 610.4878463745117, 'valid': 84.98092222213745}


  0%|          | 0/752 [00:00<?, ?it/s]

[[954045  56144]
 [ 34224 516791]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [01:26<00:00,  2.90it/s]


acc/epoch {'train': 95.61862409197819, 'valid': 94.07085813256948}
acc_class/epoch/track {'train': 95.92502694189979, 'valid': 95.59097776010378}
acc_class/epoch/shower {'train': 95.10891141065774, 'valid': 91.44876818487263}
time/epoch {'train': 618.4644982814789, 'valid': 86.45353770256042}


  0%|          | 0/752 [00:00<?, ?it/s]

[[944696  48993]
 [ 43573 523942]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [01:24<00:00,  2.98it/s]


acc/epoch {'train': 95.77709492552835, 'valid': 94.19204665117435}
acc_class/epoch/track {'train': 96.0434581501347, 'valid': 95.04305001978206}
acc_class/epoch/shower {'train': 95.3339896689878, 'valid': 92.72413100962588}
time/epoch {'train': 616.4163992404938, 'valid': 84.3405351638794}


  0%|          | 0/752 [00:00<?, ?it/s]

[[939281  41686]
 [ 48988 531249]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [01:34<00:00,  2.65it/s]


acc/epoch {'train': 95.83078227413783, 'valid': 94.45383178623678}
acc_class/epoch/track {'train': 96.08909565394497, 'valid': 96.1306081643763}
acc_class/epoch/shower {'train': 95.40106823761329, 'valid': 91.56152094042082}
time/epoch {'train': 619.3344280719757, 'valid': 94.86471128463745}


  0%|          | 0/752 [00:00<?, ?it/s]

[[950029  48347]
 [ 38240 524588]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [01:23<00:00,  3.01it/s]


acc/epoch {'train': 95.88813158390099, 'valid': 93.41937376537595}
acc_class/epoch/track {'train': 96.09866204279776, 'valid': 95.35592030105164}
acc_class/epoch/shower {'train': 95.5379062360253, 'valid': 90.07897929084452}
time/epoch {'train': 637.3516631126404, 'valid': 83.35734558105469}


  0%|          | 0/752 [00:00<?, ?it/s]

[[942373  56841]
 [ 45896 516094]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [01:25<00:00,  2.95it/s]


acc/epoch {'train': 95.96882321914653, 'valid': 94.08501387390757}
acc_class/epoch/track {'train': 96.15520317261229, 'valid': 94.49016411523583}
acc_class/epoch/shower {'train': 95.65877314666935, 'valid': 93.3861607337656}
time/epoch {'train': 621.3251233100891, 'valid': 85.01734209060669}


  0%|          | 0/752 [00:00<?, ?it/s]

[[933817  37893]
 [ 54452 535042]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [01:23<00:00,  2.99it/s]


acc/epoch {'train': 96.00212350916958, 'valid': 94.26686070494311}
acc_class/epoch/track {'train': 96.18294227147217, 'valid': 96.20214739104433}
acc_class/epoch/shower {'train': 95.70132468765115, 'valid': 90.9286393744491}
time/epoch {'train': 617.5413355827332, 'valid': 83.85375213623047}


  0%|          | 0/752 [00:00<?, ?it/s]

[[950736  51973]
 [ 37533 520962]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [01:23<00:00,  3.00it/s]


acc/epoch {'train': 96.01891285153489, 'valid': 93.90905993066889}
acc_class/epoch/track {'train': 96.20330942193296, 'valid': 94.35295450934917}
acc_class/epoch/shower {'train': 95.7121622114937, 'valid': 93.14337577561155}
time/epoch {'train': 614.4922647476196, 'valid': 83.7589910030365}


  0%|          | 0/752 [00:00<?, ?it/s]

[[932461  39284]
 [ 55808 533651]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [01:23<00:00,  3.02it/s]


acc/epoch {'train': 96.08799756897176, 'valid': 93.96978229622778}
acc_class/epoch/track {'train': 96.24874119695069, 'valid': 95.31504074295562}
acc_class/epoch/shower {'train': 95.8205944895184, 'valid': 91.64931449466344}
time/epoch {'train': 612.835547208786, 'valid': 83.18294668197632}


  0%|          | 0/752 [00:00<?, ?it/s]

[[941969  47844]
 [ 46300 525091]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [01:23<00:00,  2.99it/s]


acc/epoch {'train': 96.19847743792923, 'valid': 94.39759313965375}
acc_class/epoch/track {'train': 96.32890684977444, 'valid': 95.79294706198414}
acc_class/epoch/shower {'train': 95.98150319878071, 'valid': 91.99071447895486}
time/epoch {'train': 615.8473954200745, 'valid': 83.81257557868958}


  0%|          | 0/752 [00:00<?, ?it/s]

[[946692  45888]
 [ 41577 527047]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [04:12<00:00,  1.01s/it]


acc/epoch {'train': 96.22107023919888, 'valid': 94.14086820172123}
acc_class/epoch/track {'train': 96.35812033831414, 'valid': 95.03252656918309}
acc_class/epoch/shower {'train': 95.9930822374125, 'valid': 92.60282580048347}
time/epoch {'train': 685.7703008651733, 'valid': 252.7770073413849}


  0%|          | 0/752 [00:00<?, ?it/s]

[[939177  42381]
 [ 49092 530554]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [02:17<00:00,  1.83it/s]


acc/epoch {'train': 96.27447919310077, 'valid': 94.12876216048639}
acc_class/epoch/track {'train': 96.38435075936212, 'valid': 95.25017985993692}
acc_class/epoch/shower {'train': 96.09170370437973, 'valid': 92.19440250639252}
time/epoch {'train': 871.4039659500122, 'valid': 137.38686728477478}


  0%|          | 0/752 [00:00<?, ?it/s]

[[941328  44721]
 [ 46941 528214]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [05:09<00:00,  1.23s/it]


acc/epoch {'train': 96.29762878378561, 'valid': 94.29280222187491}
acc_class/epoch/track {'train': 96.39048833500603, 'valid': 95.43757823021869}
acc_class/epoch/shower {'train': 96.14315342283227, 'valid': 92.3181512737047}
time/epoch {'train': 1146.4794132709503, 'valid': 309.45304322242737}


  0%|          | 0/752 [00:00<?, ?it/s]

[[943180  44012]
 [ 45089 528923]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [02:26<00:00,  1.72it/s]


acc/epoch {'train': 96.2881205337726, 'valid': 93.11172659050322}
acc_class/epoch/track {'train': 96.3970030801029, 'valid': 93.9526586384881}
acc_class/epoch/shower {'train': 96.10699031695765, 'valid': 91.66118320577378}
time/epoch {'train': 1125.8567576408386, 'valid': 146.21009707450867}


  0%|          | 0/752 [00:00<?, ?it/s]

[[928505  47776]
 [ 59764 525159]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [01:32<00:00,  2.73it/s]


acc/epoch {'train': 96.39191892974796, 'valid': 94.11505479104588}
acc_class/epoch/track {'train': 96.48244910526834, 'valid': 95.69894431576827}
acc_class/epoch/shower {'train': 96.24131857300613, 'valid': 91.38296665415798}
time/epoch {'train': 715.8261830806732, 'valid': 92.025714635849}


  0%|          | 0/752 [00:00<?, ?it/s]

[[945763  49370]
 [ 42506 523565]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [01:32<00:00,  2.71it/s]


acc/epoch {'train': 96.39860040273007, 'valid': 93.95472981109451}
acc_class/epoch/track {'train': 96.49071254510176, 'valid': 95.9023302359985}
acc_class/epoch/shower {'train': 96.24536838454729, 'valid': 90.5952682241441}
time/epoch {'train': 642.0586869716644, 'valid': 92.66347932815552}


  0%|          | 0/752 [00:00<?, ?it/s]

[[947773  53883]
 [ 40496 519052]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [01:30<00:00,  2.78it/s]


acc/epoch {'train': 96.51758201775773, 'valid': 93.93512955385715}
acc_class/epoch/track {'train': 96.58949665364975, 'valid': 94.50453267278444}
acc_class/epoch/shower {'train': 96.3979493123306, 'valid': 92.95295277823837}
time/epoch {'train': 638.4565515518188, 'valid': 90.25620818138123}


  0%|          | 0/752 [00:00<?, ?it/s]

[[933959  40375]
 [ 54310 532560]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [01:36<00:00,  2.59it/s]


acc/epoch {'train': 96.54976872895041, 'valid': 94.24629965078235}
acc_class/epoch/track {'train': 96.61994451494465, 'valid': 96.20842098659374}
acc_class/epoch/shower {'train': 96.43302866582096, 'valid': 90.86179060451883}
time/epoch {'train': 642.9946506023407, 'valid': 96.84439206123352}


  0%|          | 0/752 [00:00<?, ?it/s]

[[950798  52356]
 [ 37471 520579]]


/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [01:30<00:00,  2.78it/s]


acc/epoch {'train': 96.47550158695691, 'valid': 93.88676944204602}
acc_class/epoch/track {'train': 96.56062604643093, 'valid': 95.02979451950836}
acc_class/epoch/shower {'train': 96.3338938424612, 'valid': 91.9151387155611}
time/epoch {'train': 644.6622936725616, 'valid': 90.16893649101257}
[[939150  46321]
 [ 49119 526614]]


{'epoch': [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29],
 'lr': [0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1],
 'train_time': [1497.5195684432983,
  1454.53582239151,
  1304.795478105545,
  1154.4667110443115,
  1102.3687596321106,
  1103.8568894863129,
  1112.2233304977417,
  867.8346235752106,
  621.8738601207733,
  620.86230301857,
  608.9378273487091,
  610.4895186424255,
  618.4660513401031,
  616.4182307720184,
  619.3359639644623,
  637.3534896373749,
  621.3266496658325,
  617.5429074764252,
  614.4940659999847,
  612.8371181488037,
  615.848997592926,
  685.7720775604248,
  871.405766248703,
  1146.4812502861023,
  1125.858561515808,
  715.8278558254242,
  642.0602223873138,
  638.4583523273468,


In [12]:
# test
summary, true_pid, pred_pid = trainer.evaluate(data_loader=test_loader)

  0%|          | 0/251 [00:00<?, ?it/s]/usr/local/lib64/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py:288: UserWarning: coordinates implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  + "coords into an torch.IntTensor"
100%|██████████| 251/251 [04:18<00:00,  1.03s/it]


In [13]:
# results on test
#target_names = ["track","heavy_track", "shower"]
target_names = ["track", "shower"]
print(classification_report(true_pid, pred_pid, digits=3, target_names=target_names))
print(confusion_matrix(pred_pid, true_pid))

              precision    recall  f1-score   support

       track      0.956     0.953     0.955   1046808
      shower      0.915     0.921     0.918    577258

    accuracy                          0.941   1624066
   macro avg      0.936     0.937     0.936   1624066
weighted avg      0.942     0.941     0.942   1624066

[[997503  45707]
 [ 49305 531551]]
